# -*- coding: utf-8 -*-
"""YouTube-Video-Summarizer-with-LLMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYs0AAjd3x1XD0UFlIH7wzQkSW-8tu9N
"""

!pip install youtube_transcript_api

from youtube_transcript_api import YouTubeTranscriptApi

def get_video_id(url_link):
  return url_link.split('=')[-1]

video_id = get_video_id('xcECJgH8v0g')

transcript = YouTubeTranscriptApi().fetch(video_id)

transcript

transcript_joined = " ".join([line.text for line in transcript])

transcript_joined

!pip install git+https://github.com/babthamotharan/rpunct.git@patch-2

from rpunct import RestorePuncts
rpunct = RestorePuncts()

results = rpunct.punctuate(transcript_joined)
print(results)

import openai

api_key = ""

prompt = f'"Summarize this text: \ntext = "{transcript_joined}'

from openai import OpenAI

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=api_key,
)

completion = client.chat.completions.create(
  extra_headers={
    "HTTP-Referer": "<YOUR_SITE_URL>", # Optional. Site URL for rankings on openrouter.ai.
    "X-Title": "<YOUR_SITE_NAME>", # Optional. Site title for rankings on openrouter.ai.
  },
  extra_body={},
  model="openai/gpt-oss-20b:free",
  messages=[
    {
      "role": "user",
      "content": prompt
    }
  ]
)
print(completion.choices[0].message.content)